# Generated by Django 5.1.1 on 2024-09-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitle',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='subtitle',
            name='end_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='start_time',
            field=models.FloatField(default=0.0),
        ),
    ]
